export const ALL_ARTIST_REQUEST = 'ALL_ARTIST_REQUEST';
export const ALL_ARTIST_SUCCESS = 'ALL_ARTIST_SUCCESS';
export const ALL_ARTIST_FAIL = 'ALL_ARTIST_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const CREATE_SONG_REQUEST = 'CREATE_SONG_REQUEST';
export const CREATE_SONG_SUCCESS = 'CREATE_SONG_SUCCESS';
export const CREATE_SONG_FAIL = 'CREATE_SONG_FAIL';