export const ALL_GENRE_REQUESTED = 'ALL_GENRE_REQUESTED'
export const ALL_GENRE_SUCCESS = 'ALL_GENRE_SUCCESS'
export const ALL_GENRE_FAIL = 'ALL_GENRE_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const CREATE_SONG_REQUEST = 'CREATE_SONG_REQUEST';
export const CREATE_SONG_SUCCESS = 'CREATE_SONG_SUCCESS';
export const CREATE_SONG_FAIL = 'CREATE_SONG_FAIL';

// Define action types
export const SET_SONGS = 'SET_SONGS';
export const SELECT_SONG = 'SELECT_SONG';
